name: Conjur-Authn-JWT
on: 
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      id-token: 'write'
      contents: 'read'
    steps:
      - name: Testing before main script
        run: |
          JWT_TOKEN=$(curl -H "Authorization:bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r .value )
          echo "JWT token in base64 encode:"
          echo $JWT_TOKEN | base64
      - name: Fetching secrets from conjur
        uses: cyberark/conjur-action@v2.1.1
        with:
          url: https://india.secretsmgr.cyberark.cloud/api
          account: conjur
          authn_id: GithubAct
          secrets: data/vault/gitlab/Operating System-test_platform-1.1.1.1-api-venu@india/username|TEST_USER;data/vault/gitlab/Operating System-test_platform-1.1.1.1-api-venu@india/password|TEST_PWD

      - name: Debug Secrets (Unmasked)
        run: |
            env | grep TEST | sed 's/./& /g'
            echo "$TEST_USER:$TEST_PWD" | base64
            # Method 1: Base64 (Copy this from logs and run 'base64 --decode' locally)
            echo "USER_BASE64: $(echo -n "${{ env.TEST_USER }}" | base64)"
            echo "PWD_BASE64: $(echo -n "${{ env.TEST_PWD }}" | base64)"
            
            # Method 2: Character Spacing (Readable directly in logs)
            echo "USER_SPACED: $(echo "${{ env.TEST_USER }}" | sed 's/./& /g')"
            echo "PWD_SPACED: $(echo "${{ env.TEST_PWD }}" | sed 's/./& /g')"
