name: Conjur-Authn-JWT
on: 
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      id-token: 'write'
      contents: 'read'
    steps:
      - name: Testing before main script
        run: |
          JWT_TOKEN=$(curl -H "Authorization:bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r .value )
          echo "JWT token in base64 encode:"
          echo $JWT_TOKEN | base64
      - name: Fetching secrets from conjur
        uses: cyberark/conjur-action@v2.1.1
        with:
          url: https://india.secretsmgr.cyberark.cloud/api
          account: conjur
          authn_id: GithubAct
          secrets: data/vault/gitlab/gituser1-gitlabsafe/address|TEST_USER
      - name: Checking the result
        run: |
          echo Show env detail:
          env | grep TEST
          echo "$TEST_USER"
          $TenantUrl = "https://abg4316.id.cyberark.cloud"
          $ClientId = "api-venu@india"
          $ClientSecret = "Cyberark1"
          $Body = @{
          grant_type    = "client_credentials"
          client_id     = $ClientId
          client_secret = $ClientSecret
          }
          $Response = Invoke-RestMethod `
          -Method Post `
          -Uri "$TenantUrl/OAuth2/token/test" `
          -ContentType "application/x-www-form-urlencoded" `
          -Body $Body
          $AccessToken =  $Response.access_token
          echo $AccessToken
